version: '3'
services:
  weblate:
    image: weblate/weblate
    volumes:
    - weblate-data:/app/data
    - weblate-cache:/app/cache
    env_file:
    - ./environment
    restart: always
    depends_on:
    - database
    - cache
  database:
    # The official image has this set to ':15-alpine', but I haven't been able to find out how to migrate the Postgres instance yet :P.
    image: postgres:14-alpine
    env_file:
    - ./environment
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:7-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
volumes:
  weblate-cache: {}
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
